# Title of the app (shown on top left)
main_title: "RESQUE CP-S2"

# Background color of the app
background_color: "#ffeeee"

# Maximum number of papers that are expected by the committee
max: 10

# Number of top papers that must be selected
max_top_papers: 3

# Minimum number of papers that must be entered before 
# showing a warning is shown at the scoring box
min_RO_warning_threshold: 0

# Show the welcome message (text is defined in config/instructions.md)
show_instruction: false

# Show the beta warning message
show_beta_warning: false

# Logo
image_url: https://upload.wikimedia.org/wikipedia/commons/0/06/LMU_Muenchen_Logo.svg

meta:
  sources: ["packs/core-meta.json"]
  exclude: ["AcademicAgeBonus", "AcademicAgeBonus_Explanation", "HonestyDisclaimer"]
  config:
    min_indicators_warning_threshold: 0

pubs:
  sources: ["packs/core-pubs.json"]
  exclude: ["P_TopPaper", "P_Stimuli", "P_Sample_RepresentativenessRelevance", "P_Sample_Representative", "P_Sample_Representative_Details", "P_MultiStudy_Note2", "P_Power_Info", "P_PowerConsiderations", "P_SampleSize", "P_MeritStatement_Info", "P_MeritStatement", "P_ImpactStatement_Info", "P_ImpactStatement", "P_Theorizing"]
  config:
    min_indicators_warning_threshold: 0

data:
  sources: ["packs/core-data.json"]
  config:
    min_indicators_warning_threshold: 0

software:
  sources: ["packs/core-software.json"]
  config:
    min_indicators_warning_threshold: 0

score_categories:
  - title: "Theorizing & Formal Modeling"
    cue: "Theorizing"

  - title: "Open Data"
    cue: "Data"

  - title: "Open Materials"
    cue: "OpenMaterials"

  - title: "Preregistration"
    cue: "Prereg"
    
  - title: "Reproducible Code & Verification"
    cue: "ReproducibleScripts|IndependentVerification"