# Title of the app (shown on top left)
main_title: "RESQUE Dev"

# Background color of the app
background_color: "#c3e8e2"

# Maximum number of papers that are expected by the committee
max: 10

# Number of top papers that must be selected
max_top_papers: 3

# Minimum number of papers that must be entered before 
# showing a warning is shown at the scoring box
min_RO_warning_threshold: 0

# Show the welcome message (text is defined in config/instructions.md)
show_instruction: true

# Show the beta warning message
show_beta_warning: false
image_url: https://www.tu-chemnitz.de/phil/iesg/ringvorlesung/RV2021/TUC_Logo.jpg

hide_score: false

# If "true": The merit statement and impact statement are only required 
# for publications that are selected as "top publications"
statements_only_for_top_publications: true

meta:
  sources: ["packs/core-meta.json"]
  exclude: ["RaterType "]
  config:
    min_indicators_warning_threshold: 0

pubs:
  sources: ["packs/core-pubs.json", "packs/EP/EP-clinical_psychology.json"]
  exclude: ["P_IndependentVerification", "P_Stimuli", "P_ImpactStatement_Info", "P_ImpactStatement", "P_Theorizing", "sep_before_correctness", "P17P18SEP", "P19P20SEP", "CP_Methods_NullResults", "P_Sample_CoG", "P_Sample_CrossCultural", "stimsep"]
  config:
    min_indicators_warning_threshold: 0

data:
  sources: ["packs/core-data.json"]
  config:
    min_indicators_warning_threshold: 0

software:
  sources: ["packs/core-software.json"]
  config:
    min_indicators_warning_threshold: 0

score_categories:
  - title: "Open Data"
    cue: "Data"
    color: '#beaed4'

  - title: "Open Materials"
    cue: "OpenMaterials"
    color: '#fdc086'

  - title: "Preregistration"
    cue: "Prereg"
    color: '#d95f02'

  - title: "Reproducible Code"
    cue: "ReproducibleScripts"
    color: '#386cb0'

  - title: "Methodological Rigor"
    cue: "_Methods_"
    color: '#f0027f'
